### ISSUE TITLE
problem menu information

### ISSUE THREAD

**Issue by budinev** [Hains/openvision-dm920-python3#17]
hi I'm testing the master branch image I have a crash on the information menu

**Comment by Hains** [comment]
Can you post crashlog?  It's in /hdd/ or /home/root/.

/usr/lib/enigma.info file is missing some information.  The crashlog can tell us what.

Can you post /usr/lib/enigma.info file?

With new Boxinfo system, an online update isn't sufficient in some cases and  you need to do a clean image flash.

If enigma.info is missing image variable, try: 

git config --global --add safe.directory /home/ <yourusername> /openpli-dm920-python3 

to you build-server. 

Edit: Between /home/  and /openpli-dm920-python3 type your username.

e.g.  /home/budinev/openpli-dm920-python3

**Comment by budinev** [comment]
[eDVBPESReader] DMX_SET_PES_FILTER pid=ffffffff:  Invalid argument
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 77, in action
    return ActionMap.action(self, contexts, action)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
    res = self.actions[action]()
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 56, in okbuttonClick
    selection[1]()
  File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 10, in __call__
    return self.fnc(*self.args + args, **newkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 69, in runScreen
    self.openDialog(*eval(arg[1]))
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 75, in openDialog
    self.session.openWithCallback(self.menuClosed, *dialog)
  File "/usr/lib/enigma2/python/StartEnigma.py", line 295, in openWithCallback
    dlg = self.open(screen, *arguments, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/StartEnigma.py", line 305, in open
    dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/StartEnigma.py", line 248, in instantiateDialog
    return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/StartEnigma.py", line 265, in doInstantiateDialog
    dlg = screen(self, *arguments, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/Screens/About.py", line 39, in __init__
    AboutText += _("OE Version: ") + about.getOEVersionString() + "\n"
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/enigma2/python/Components/About.py", line 95, in getOEVersionString
    return BoxInfo.getItem("oe").title()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'title'
[ePyObject] (CallObject(<bound method NumberActionMap.action of <Components.ActionMap.NumberActionMap object at 0xadd03d30>>,('OkCancelActions', 'ok')) failed)

**Comment by budinev** [comment]
the crash also occurs with pli develop zgemma images

**Comment by budinev** [comment]
build python 3.12 dm920  ok no problem

**Comment by Hains** [comment]
I had that problem as well with OpenPLI build-env for Gigablue 4kTrio.

git config --global --add safe.directory /home/hains/openpli-oe-core

did solve the issue.

Edit /usr/lib/enigma.info.
Line starting with: 

oe=

(for me line 48) must be:

oe=hardknott (3.3.6)
